name = input("what is your name? ")
print("hi " +name)
color = input("what is your favorite color? ")
print(name+ " likes " +color)
birth_year = input("enter your Birth year:")
age = 2022 - int(birth_year)
print("your age is " + str(age))
print(type(age))
